server:
  port: 8086

spring:
  application:
    name: service-driver-user

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/service-driver-user?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: 123456
    password: 123456

  cloud:
    nacos:
      server-addr: 127.0.0.1:8848